---
title: "Lab 10"
author: "Hollie Pennington"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
library(tidyverse)
library(janitor)
library(usethis)
library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```

## beepr:beep()
Use 'beep()' to give yourself an audio alert. 

## for loop + beep

```{r}
for (i in rev(seq(1:9999))) {
  print(paste(i,"bottles of beer on the wall"))
}

beep(4)
```

# praise in nice

```{r}
praise("${EXCLAMATION}!!! This code works ${adverb_manner}!")

praise("Holy ${creating}, Batman - this code works ${ADVERB_MANNER}!")
```

## cowsay:: say to have characters say something 

```{r}
say("You'll be okay!", by = "bat")
```

## usethis for everything 

cowsay::say(praise::praise("You are ${ADJECTIVE}!"), by = "cat")

R project first, then git & GitHub Repo. 

- usethis::use_git()
- usethis::use_github()

## paletteer: aggregated color palettes

```{r}
storms %>%
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n = 10, min_pressure) %>% 
  ggplot(aes(x = min_pressure, y = name)) + 
  geom_col(aes(fill = name)) + 
  scale_fill_paletteer_d("palettesForR::Pastels")
```

## Map of Jornada LTER Vegetation 

```{r}
jornada_veg <- read_sf("doc.kml") %>%
  select(Name) %>% 
  clean_names()

ggplot() + 
  geom_sf(data = jornada_veg, aes(fill = name), color = NA) + 
  theme_minimal() + 
  scale_fill_paletteer_d("ggthemes::manyeys") + 
  labs(title = "Jornada Basin LTER Vegetation")

# Update this map: 
# Each vegetation type has a different fill color 
# Update theme 
# Customize the color palette

ggsave(filename = "my_awesome_jornada_map.png", width = 8, height = 5)
```



